### ISSUE TITLE
Adding options `keyName`

### ISSUE THREAD

**Issue by Atinux** [declandewet/vue-meta#12]
Hi!

I think it could be great to set the keyName as an option when installing `vue-meta`:

```js
import Meta from 'vue-meta'

var options = {
  keyName: 'head'
}
Vue.use(Meta, options)
```

So then, in my components, I can do:
```html
<script>
  export default {
    head: {
      title: 'My Example App',
      htmlAttrs: { lang: 'en' }
    }
  }
</script>
```

I want to implement it in nuxt.js as similar as in next.js, the component name is <Head>, so a key `head` seems the best name to making it similar (even if vue-meta can update more than inside the <head>, which rocks 🚀 )

I you like the idea, I can try to make a pull request?

**Comment by Atinux** [comment]
**Better idea: **

Do you think it's possible that I create my own component `<nuxt-head>` which change the `metaInfo` data of the component *or* talk to `vue-meta` to tell it the metaInfo data ?

I believe that `vue-meta` load the the `metaInfo` when the Component is instantiated, is there any way to make the metaInfo reactive? Or to call something like `this.$meta.refresh()`?

**Comment by declandewet** [comment]
Hi @Atinux - I do have plans to support these `options`:

- `keyName`: the name of the meta info key (default: `metaInfo`)
- `attribute`: the attribute that vue-meta uses to identify the tags it cares about (default: `data-vue-meta`
- `ssrAttribute`: the attribute that vue-meta uses to determine server rendering and if it should halt on client-side hydration on initial render (default: `data-vue-meta-server-rendered`)
- `tagListId`: the attribute that vue-meta uses to determine overrides (default: `vmid`)

On the topic of componentiz-ing `vue-meta`, as I said on Gitter, I've considered this but it requires a _lot_ more code, but wouldn't say no to a PR.

I am however interested in the notion of making `metaInfo` reactive - it would certainly help the issue of asynchronous action bugs as seen in #13

I do have some ways of fixing this already, like emitting events, but I'm betting theres a more "Vue" way of doing this. Care to offer your 2c? I think rubber ducking on this issue will help move things along :smile:

**Comment by Atinux** [comment]
It's great for the `options` 👏 

Actually, I think the easiest wait to resolve #10, #13 and also making the `<nuxt-head>` component possible will be to add a `refresh()` method to `this.$meta`, this method will only to:
```js
// src/server/$meta.js
import getMetaInfo from '../shared/getMetaInfo'
import updateClientMetaInfo from '../client/updateClientMetaInfo'

function refresh () {
  const info = getMetaInfo(this.$root)
  // update the meta info
  updateClientMetaInfo(info)
}
```

Example:
```js
export default {
  data () {
    title: 'Default title'
  },
  mounted () {
    setTimeout(() => {
      this.title = 'Title updated'
      this.$meta.refresh()
    }, 2000)
  },
  metaInfo: {
    title () { return this.title }
  }
}
```

This should make the title of the page to Default title and then after 2 seconds to Title updated.

**Comment by declandewet** [comment]
It would have to be `$metaRefresh`, as `$meta` is a function (it cannot be a regular property) used for SSR injection.

Also, due to the way I'm grabbing the deeper-most nested components, `data` is prone to being overwritten and thus `return this.title` in your example above might evaluate to `null` despite the presence of the default data.

It's a weird little tradeoff so I'm trying to look for a more robust solution to this issue :smile:

**Comment by Atinux** [comment]
I changed my example to be: `this.$meta().refresh()`

I'm not sure why `this.title` will be overwritten by any other deeper component. You give the context of the actual instance while calling the title() method right?

I think it's a bug if `this.title` return null despite the precense of the default data.

**Comment by Atinux** [comment]
I believe `$meta()` should be shared between client and server.

`.inject()` is only a JavaScript function an can be called from the client-side without problems
`.refresh()` can be called from the client-side, and if from the server-side, will call `.inject()`

**Comment by declandewet** [comment]
@Atinux 

> I'm not sure why this.title will be overwritten by any other deeper component. You give the context of the actual instance while calling the title() method right?

Because of inconsistencies and a hack. A few hours ago, I tested to see if calling `this.title` would work in an asynchronous dispatch, but it did not, despite having the default `data` ready.

Originally, I iterated through each component in the render hierarchy recursively, calling `fn = fn.bind(component)` to set the context inside `getComponentOption` when a new component was encountered - and then finally evaluated that function call inside `getMetaInfo`, but that led to bugs #9 & #10. I remedied that in [this commit](https://github.com/declandewet/vue-meta/commit/6ad56ec73e428316c2e4c115274ca655024c2810#diff-b93404865cb34a7e502174b08d74443eR76), namely in the `getMetaInfo` [method](https://github.com/declandewet/vue-meta/blob/fa290273dfd00a7368720d5c2a5074063b6de700/src/shared/getMetaInfo.js#L75-L84
).

As you can see, I do a recursive shallow-merge of the root component with all of its children components, each child overwriting the context of its parent. This franken-component is what gets placed into the context of the function form of each `metaInfo` prop. As crude and hacky as it is, it seems to be the only way to get all the right context information in place, but at the expense of reliable data.

 > I think it's a bug if this.title return null despite the precense of the default data.

I think so too, but I would rather have that than not have compatibility with Vuex + render functions. I'm very open to suggestion here and am even trying to find a better way of doing this as we speak.

> I believe $meta() should be shared between client and server.

It technically already is, but I didn't intend for it to be. I'm not saying I'm against it, just that it would have to be returned as its own property like the `inject` method, as you've suggested :smile:

> .inject() is only a JavaScript function an can be called from the client-side without problems
.refresh() can be called from the client-side, and if from the server-side, will call .inject()

My only concern with `.refresh()` is that it's verbose - I'm sure there's a better way to handle asynchronous use-cases, one that doesn't require the use of an extra method. I'm studying the code behind Vue's reactivity system - I've got something very miniscule working as a POC, but Vue does not like it one bit - I'm getting warnings telling me not to use `Vue.set` when I could just use `data`. 🎱

**Comment by declandewet** [comment]
Hey @Atinux - After much trial and error, I gave up on trying to find a magical way of solving this and I added the `refresh` method as you've suggested in https://github.com/declandewet/vue-meta/commit/076832cbd6b2ffcc804fcdb2a9edd438c58573b5

**Comment by Atinux** [comment]
Hey @declandewet 

Nice work on implementing it so fast!

I think you're going to laugh... I just found a solution to update *magically* the meta without having to call `refresh()` 😄 

All you have to do is to set `metaInfo` as a method instead:
```js
metaInfo: function () {
  return {
    title: this.title,
    meta: [{ name: 'description', content: this.description }]
  }
}
```

Then, you just have to add 2 methods in your mixin in `src/shared/plugin.js`:
```js
Vue.mixin({
  beforeCreate () {
    if (typeof this.$options.metaInfo === 'function') {
      this.$options.computed.$metaInfo = this.$options.metaInfo;
    }
  },
  created () {
    if (this.$metaInfo) {
      this.$watch('$metaInfo', (metas) => {
        this.$meta.refresh()
      })
    }
  }
  beforeMount () {
    // batch potential DOM updates to prevent extraneous re-rendering
    window.cancelAnimationFrame(requestId)

    requestId = window.requestAnimationFrame(() => {
      requestId = null
      this.$meta().refresh()
    })
  }
})
```

I did not tested it inside `vue-meta`, but you can see my demo on JSfiddle here: https://jsfiddle.net/Atinux/ct7m3463/

What do you think?

**Comment by declandewet** [comment]
That's brilliant @Atinux - why don't you PR it in? :D If not, I will try get it working on a feature branch as soon as I've investigated #14.

**Comment by Atinux** [comment]
I would but actually I have to work on something else sorry. At first I wanted to congratulate you for implementing `refresh()` but then the idea of the computed property popped up in my mind so I had to try it and let you know 😄

**Comment by Atinux** [comment]
And before implementing it, it should use the keyName instead of the `metaInfo` property:
```js
if (typeof this.$options[options.keyName] === 'function') {
  this.$options.computed.$metaInfo = this.$options[options.keyName];
}
```

If I got some time, I will PR with pleasure!

**Comment by declandewet** [comment]
The more I look at this, and the more I look at #14, the more I'm starting to think that `metaInfo` should just always be a function. It would simplify a lot of code and get rid of a lot of potential bugs.

**Comment by Atinux** [comment]
I think it should be either an object (with static data) or a function.

This would do the trick:
```js
beforeCreate () {
    var metaInfo = this.$options[options.keyName]
    if (metaInfo === 'object') {
       metaInfo = function () { return metaInfo }
    }
    if (metaInfo === 'function') {
      this.$options.computed.$metaInfo = metaInfo;
    }
}
```

**Comment by declandewet** [comment]
Way ahead of you @Atinux - #15 😛 

I'm not going to be implementing the `computed` / `watch` stuff yet though. I'll be doing that after I support options for changing the key/attribute names.

**Comment by Atinux** [comment]
Nice work @declandewet 👏 

It makes sense to implement the options before. I'm thrilled to see it working with computed/watch so we won't have to call `this.$meta.refresh()` anymore :)

I just think that we should be careful if a parent component data change (and use it in metaInfo) and one child component use this data as well inside its metaInfo), maybe using _.debounce(this.$meta.refresh.bind(this), 100) to make sure that we avoid calling twice for one change.

**Comment by declandewet** [comment]
@Atinux If I move the batching logic into `$meta().refresh`, then that problem will be solved :smile:

**Comment by declandewet** [comment]
@Atinux `vue-meta` supports custom options now. I also moved the watch suggestion to its own issue: #17
