### ISSUE TITLE
opencollective?

### ISSUE THREAD

**Issue by gdi2290** [declandewet/vue-meta#176]
can you make an open-collective page?

https://opencollective.com

**Comment by Atinux** [comment]
Hi @gdi2290 

Actually, I am the only maintainer of `vue-meta` right now since Declan Dewet had a terrible accident last year and he is still in recovery.

If you want to make donation, right now, you can give to Nuxt.js Open Collective since we depend of vue-meta into our core: https://opencollective.com/nuxtjs

Thank you BTW for asking :)
