### ISSUE TITLE
Twitter cards meta bug?

### ISSUE THREAD

**Issue by Atinux** [declandewet/vue-meta#27]
Website: https://nuxt-head-elements.now.sh/about

You can take a look at the source code, there is:
```html
<meta n-head="true" charset="utf-8"/>
<meta n-head="true" name="viewport" content="width=device-width, initial-scale=1"/>
<meta n-head="true" hid="description" name="description" content="About page description"/>
<meta n-head="true" name="twitter:card" content="summary"/>
<meta n-head="true" name="twitter:site" content="@nuxt_js"/>
<meta n-head="true" name="twitter:title" content="Nuxt.js Twitter Card"/>
<meta n-head="true" name="twitter:description" content="Nuxt.js lets you handle custom headers for your app with vue-meta"/>
<meta n-head="true" name="twitter:image" content="https://avatars0.githubusercontent.com/u/23360933?v=3"/>
<meta n-head="true" name="twitter:image:alt" content="Nuxt.js logo"/>
<title n-head="true">About Page - Nuxt.js</title>
```

But if you try to check the meta tags here: https://cards-dev.twitter.com/validator

It says that no meta tags has been found.

Same for some other meta checker like http://www.seocentro.com/tools/search-engines/metatag-analyzer.html

Do you think it's because of the `n-head` attribute or `hid`?

**Comment by declandewet** [comment]
Hi @Atinux - I've run into this issue before on a few projects long before making `vue-meta` - I think the issue here is that your response is not sending a `Content-Type` header of `text/html`

<img width="462" alt="screen shot 2016-11-20 at 1 43 02 pm" src="https://cloud.githubusercontent.com/assets/1918632/20462478/70789892-af27-11e6-86b1-f88e53304f14.png">

Try adding that header and see if it works?

For reference: https://twittercommunity.com/t/have-metatag-and-robots-txt-so-why-does-fetching-fail/22379/14

**Comment by Atinux** [comment]
Fixed by adding `Content-Type` `text/html`, you rock, thank you!
