### ISSUE TITLE
How can we use it with vue-class-component?

### ISSUE THREAD

**Issue by vishr** [declandewet/vue-meta#88]
I am trying examples with https://github.com/vuejs/vue-class-component but it doesn't work like below:

```js
export default class App extends Vue {
    metaInfo = {
      title: 'Title'
    }
}
```

**Comment by vishr** [comment]
I trying examples with https://github.com/vuejs/vue-class-component but it doesn't work like below:

```js
export default class App extends Vue {
    metaInfo = {
      title: 'Title'
    }
}
```

**Comment by vishr** [comment]
It works like below:

```js
@Component({
    metaInfo: {
      title: title
   })
```

**Comment by Atinux** [comment]
@vishr please look at https://github.com/vuejs/vue-class-component#adding-custom-hooks

```js
import Component from 'vue-class-component'

Component.registerHooks([
  'metaInfo'
])
```

**Comment by vishr** [comment]
@Atinux Thanks for your response, I will have a look it.

**Comment by romandragan** [comment]
@vishr, I use it like that and it works fine on client rendering:

```
@Component
export default class Home extends Vue {

    public metaInfo(): any {
        return {
            meta: [
                { name: 'description', content: 'Test description' },
                { name: 'keywords', content: 'Test keywords' },
            ],
            title: 'Test Title',
        };
    }
}
```

But it does not work in SSR. While doing
```
const { title, meta } = context.meta.inject();
```
in `server.js` it says that `context.meta` is undefined.

Maybe @declandewet or @Atinux can help us?

**Comment by derat** [comment]
Just to mention it in case someone else runs into it, the vue-class-component docs on additional hooks are now at https://class-component.vuejs.org/guide/additional-hooks.html, and it's essential that you register the `metaInfo` hook before defining any components (as described in the docs). Otherwise, metadata won't be updated when a component is initially mounted (although it will update after hot-reload), and you'll get `This vue app/component has no vue-meta configuration` if you manually call `this.$meta().refresh()`.
